insert into public.products (
  slug,
  name,
  category,
  store_section,
  base_price,
  description,
  summary,
  lead_time,
  featured,
  supports_gift_wrap,
  supports_custom_vinyl,
  active
)
values
  (
    'adult-essential-tee',
    'Unisex Essential T-Shirt',
    'Clothing',
    'personalized',
    280,
    'High-quality cotton T-shirt designed for everyday wear and custom printing, with long or short sleeve options.',
    'Unisex essential tee in XS-2XL with black, white, navy, and core event colours.',
    '2-4 business days',
    true,
    true,
    false,
    true
  ),
  (
    'custom-vinyl-sticker',
    'Custom Vinyl Sticker',
    'Stickers',
    'personalized',
    0,
    'Custom-cut vinyl sticker priced by custom dimensions for branding, labels, and decor. Available in a wide range of vinyl colours.',
    'Made-to-size vinyl sticker with live price calculation. Choose your vinyl colour.',
    '2-3 business days',
    true,
    false,
    true,
    true
  ),
  (
    'wine-tumbler',
    'Wine Tumbler',
    'Drinkware',
    'ready-made',
    230,
    'Stylish insulated wine tumbler ready for names, bridal gifts, and gifting sets.',
    'Elegant custom tumbler for gifting and celebrations.',
    '3-5 business days',
    true,
    true,
    false,
    true
  ),
  (
    'ceramic-coffee-mug',
    'Normal Coffee Mug',
    'Drinkware',
    'ready-made',
    60,
    'Standard ceramic mug suitable for everyday use, custom branding, and affordable gifting.',
    'Classic coffee mug for names, logos, photos, and event gifting.',
    '2-4 business days',
    false,
    true,
    false,
    true
  ),
  (
    'colour-business-cards',
    'Business Cards (Single Sided Colour)',
    'Marketing Essentials',
    'personalized',
    110,
    'Full-colour business cards that elevate small business branding.',
    'Quantity pricing: 50 R110 | 100 R210 | 500 R350.',
    '2-4 business days',
    false,
    false,
    false,
    true
  )
  (
    'custom-socks',
    'Socks',
    'Accessories',
    'personalized',
    72,
    'Custom-printed socks available in short (25cm) ankle length or long (40cm) length. Perfect for gifting, teams, and personalized keepsakes.',
    'Short socks R72 | Long socks R75. Choose your length variant.',
    '3-5 business days',
    false,
    true,
    false,
    true
  ),
  (
    'buddy-sippy-cup',
    'Buddy Sippy Cup',
    'Drinkware',
    'ready-made',
    170,
    'Compact kids drinkware option for everyday use, nursery gifts, and custom keepsakes. Available in blue or pink.',
    'Affordable baby and kids cup with personalization-ready printing. Choose blue or pink.',
    '2-4 business days',
    false,
    true,
    false,
    true
  ),
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  store_section = excluded.store_section,
  base_price = excluded.base_price,
  description = excluded.description,
  summary = excluded.summary,
  lead_time = excluded.lead_time,
  featured = excluded.featured,
  supports_gift_wrap = excluded.supports_gift_wrap,
  supports_custom_vinyl = excluded.supports_custom_vinyl,
  active = excluded.active;
